import { Product } from "./types";

/**
 * Curated starter catalog for the camping store.
 *
 * Cost prices (costUsd) are research-based CJdropshipping-range estimates
 * (priceSource: "estimated"). Once the CJ_API credentials are configured and
 * this app runs somewhere with outbound network access to CJdropshipping,
 * `/api/products` will replace these with live supplier prices from CJ and
 * flip priceSource to "cj-live" automatically - see lib/cj.ts.
 */
export const products: Product[] = [
  {
    slug: "portable-electric-camping-shower",
    nameHe: 'מקלחת קמפינג נטענת ניידת חשמלית 5000mAh עמידה למים',
    nameEn:
      "Outdoor Camping Shower Portable Electric Shower Gadgets Waterproof 5000mAh Rechargeable Battery Powered For Hiking Traveling",
    descriptionHe:
      "משאבת מקלחת ניידת וחשמלית לקמפינג וטיולים - מתחברת לכל דלי או מיכל מים ויוצרת זרם מקלחת נוח. סוללה נטענת 5000mAh בטעינת USB, עמידה למים, קלה לנשיאה. מושלמת לטיולי שטח, קמפינג, רחיצת כלבים ושטיפת רכב.",
    category: "shower-hygiene",
    cjPid: "1797824294479736832",
    cjVid: "1797824294563622912",
    costUsd: 10.15,
    shippingUsd: 14.05,
    etaDays: [9, 23],
    priceSource: "cj-live",
    icon: "shower",
    imageUrl: "https://oss-cf.cjdropshipping.com/product/2024/07/22/07/10630342-c726-42a7-9dba-41e1ce220720.jpg",
    featured: true,
    specsHe: [
      "סוללת ליתיום 5000mAh, טעינה בכבל USB",
      "עמיד למים (IPX7)",
      "זמן פעולה: כ-70-90 דקות בטעינה מלאה",
      "משקל קל, מתאים לתרמיל גב",
    ],
    packageContentsHe: [
      "משאבת מים חשמלית - יחידה אחת",
      "ראש מקלחת",
      "2 טבעות אטימה",
      "מעמד תלייה",
      "צינור PVC",
      "כבל טעינה USB",
    ],
  },
  {
    slug: "led-camping-lantern-rechargeable",
    nameHe: "פנס קמפינג LED נטען מתקפל לתלייה באוהל",
    nameEn: "Rechargeable Folding LED Camping Lantern Tent Light",
    descriptionHe:
      "פנס LED מתקפל וקומפקטי לאוהל, נטען ב-USB עם מספר עוצמות תאורה ווו לתלייה. תאורת חירום מעולה לקמפינג, הפסקות חשמל וטיולי לילה.",
    category: "lighting",
    cjPid: "2506290947141613500",
    cjVid: "2506290947141613700",
    costUsd: 1.53,
    shippingUsd: 4.23,
    etaDays: [9, 23],
    priceSource: "cj-live",
    icon: "lantern",
    imageUrl: "https://oss-cf.cjdropshipping.com/product/2025/06/29/09/48f59e72-b283-4b42-8c67-381bdacb249d_trans.jpeg",
    featured: true,
    specsHe: ["נטען USB-C", "3 מצבי תאורה", "מתקפל לגודל כף יד", "וו תלייה מובנה"],
    packageContentsHe: ["פנס LED - יחידה אחת", "כבל טעינה", "הוראות הפעלה"],
  },
  {
    slug: "mini-windproof-camping-stove",
    nameHe: "כיריים גז ניידות מיני עמידות ברוח לקמפינג",
    nameEn: "Mini Portable Windproof Camping Gas Stove",
    descriptionHe:
      "כיריים גז קומפקטיות ומתקפלות לבישול בשטח, עמידות ברוח, קלות משקל וקלות להרכבה. מתאימות לגסטרו קמפינג, טרקים וחירום.",
    category: "cooking",
    costUsd: 15.9,
    shippingUsd: 9,
    etaDays: [14, 22],
    priceSource: "estimated",
    icon: "stove",
    imageUrl: "https://cf.cjdropshipping.com/17534880/1949028266107211776.jpg",
    specsHe: ["מתקפלות לגודל כיס", "עמידות ברוח", "משקל: כ-200 גרם", "כולל תיק נשיאה"],
    packageContentsHe: [
      "גוף הכיריים המתקפל - יחידה אחת",
      "תיק נשיאה",
      "⚠️ לא כולל מיכל גז - יש לרכוש בנפרד בארץ (לא ניתן למשלוח בדואר בינלאומי מסיבות בטיחות)",
    ],
  },
  {
    slug: "inflatable-travel-pillow",
    nameHe: "כרית טיולים מתנפחת קומפקטית",
    nameEn: "Inflatable Compact Travel & Camping Pillow",
    descriptionHe:
      "כרית מתנפחת קלת משקל ואולטרה-קומפקטית לתרמיל, מתאימה לקמפינג, טיסות וטיולי שטח. מתקפלת לגודל כף יד.",
    category: "sleep-comfort",
    cjPid: "1400751666202021888",
    cjVid: "1400766651703627776",
    costUsd: 4.79,
    shippingUsd: 5.82,
    etaDays: [9, 23],
    priceSource: "cj-live",
    icon: "pillow",
    imageUrl: "https://cf.cjdropshipping.com/1622799260520.jpg",
    specsHe: ["מתנפחת/מתרוקנת בשניות", "משקל: כ-80 גרם", "כולל שקית נשיאה"],
    packageContentsHe: ["כרית מתנפחת - יחידה אחת", "שקית נשיאה עם מיתר הידוק"],
  },
  {
    slug: "solar-power-bank-20000mah",
    nameHe: "סוללת גיבוי סולארית 20000mAh לקמפינג",
    nameEn: "Solar Power Bank 20000mAh Outdoor Camping Charger",
    descriptionHe:
      "סוללת גיבוי בקיבולת גבוהה עם פאנל סולארי לטעינה בשטח, פנס LED מובנה ומספר יציאות USB. חיוני לכל טיול קמפינג ממושך.",
    category: "power",
    costUsd: 17.9,
    shippingUsd: 10,
    etaDays: [14, 24],
    priceSource: "estimated",
    icon: "power-bank",
    imageUrl: "https://cf.cjdropshipping.com/f861a9f2-bc34-4cf3-a578-e2694ecfe05f.jpg",
    featured: true,
    specsHe: ["קיבולת 20000mAh", "פאנל טעינה סולארי", "פנס LED מובנה", "2 יציאות USB יציאה"],
    packageContentsHe: ["סוללת גיבוי - יחידה אחת", "כבל טעינה USB"],
  },
  {
    slug: "double-camping-hammock",
    nameHe: "ערסל קמפינג זוגי מבד פרשוט",
    nameEn: "Double Portable Parachute Nylon Camping Hammock",
    descriptionHe:
      "ערסל זוגי עמיד וקל משקל מבד ניילון פרשוט, כולל רצועות תלייה וקרביטנים. מתקפל לתיק נשיאה קטן - מושלם לטיולים וקמפינג.",
    category: "sleep-comfort",
    cjPid: "1426814502627840000",
    cjVid: "1426814505207336960",
    costUsd: 7.96,
    shippingUsd: 14.62,
    etaDays: [9, 23],
    priceSource: "cj-live",
    icon: "hammock",
    imageUrl: "https://cf.cjdropshipping.com/d062f80c-d6f7-4444-8019-cf57fe415589.jpg",
    specsHe: ["עומס מקסימלי: עד 200 ק\"ג", "כולל רצועות וקרביטנים", "מתקפל לגודל כף יד"],
    packageContentsHe: [
      "ערסל - יחידה אחת",
      "2 רצועות תלייה מתכווננות (אורך כ-2 מ׳ כל אחת)",
      "2 קרבינרים",
      "שקית נשיאה",
    ],
  },
  {
    slug: "usb-led-headlamp",
    nameHe: "פנס ראש LED נטען USB עמיד למים",
    nameEn: "USB Rechargeable Waterproof LED Headlamp",
    descriptionHe:
      "פנס ראש קל וחזק, נטען ב-USB, עמיד למים ומושלם לטיולי לילה, ריצה, קמפינג ועבודה בשטח. רצועה מתכווננת ונוחה.",
    category: "lighting",
    costUsd: 7.2,
    shippingUsd: 5,
    etaDays: [12, 20],
    priceSource: "estimated",
    icon: "headlamp",
    imageUrl: "https://cf.cjdropshipping.com/a9d666c4-c8e9-49e0-a121-dce4de0ba234.jpg",
    specsHe: ["נטען USB", "עמיד למים IPX5", "מספר מצבי תאורה", "משקל קל במיוחד"],
    packageContentsHe: ["פנס ראש - יחידה אחת", "רצועת ראש מתכווננת", "כבל טעינה USB"],
  },
  {
    slug: "folding-camping-chair",
    nameHe: "כיסא קמפינג מתקפל וקומפקטי",
    nameEn: "Compact Folding Camping Chair",
    descriptionHe:
      "כיסא קמפינג נוח, יציב וקל לנשיאה, מתקפל לתיק קומפקטי עם רצועת נשיאה. מתאים לפסטיבלים, חופים וטיולי שטח.",
    category: "furniture",
    cjPid: "7A1F4C59-B38D-4B5C-9F20-F8D154D43AD6",
    cjVid: "1BAC158A-F59C-4733-BD9C-DC59A9433467",
    costUsd: 15.45,
    shippingUsd: 16.1,
    etaDays: [9, 23],
    priceSource: "cj-live",
    icon: "chair",
    imageUrl: "https://cf.cjdropshipping.com/1533363748375-TIM%E6%88%AA%E5%9B%BE20180804142023.png",
    specsHe: ["עומס מקסימלי: עד 120 ק\"ג", "מתקפל לתיק נשיאה", "מסגרת אלומיניום קלה"],
    packageContentsHe: ["כיסא מתקפל - יחידה אחת (רגליים מאלומיניום, לא כולל תיק נשיאה נפרד)"],
  },
  {
    slug: "portable-water-filter-straw",
    nameHe: "קש סינון מים ניידת להישרדות וטיולים",
    nameEn: "Portable Survival Water Filter Straw",
    descriptionHe:
      "קש סינון מים ניידת המסננת חיידקים וזיהומים ישירות ממקור מים טבעי - ציוד חיוני לכל תיק חירום או טיול שטח.",
    category: "tools-safety",
    cjPid: "15C7593C-585B-4D11-9ED2-0A1B0C99B84F",
    cjVid: "65B6ED50-794B-4729-AA89-680EE410305A",
    costUsd: 8.0,
    shippingUsd: 4.69,
    etaDays: [9, 23],
    priceSource: "cj-live",
    icon: "water-filter",
    imageUrl: "https://cf.cjdropshipping.com/2054/48845080815735.jpg",
    specsHe: ["מסננת עד 99.9% מחיידקים", "אורך חיים: כ-1500 ליטר", "קלה ואולטרה-קומפקטית"],
    packageContentsHe: ["קש סינון מים - יחידה אחת בלבד"],
  },
  {
    slug: "ultralight-inflatable-sleeping-pad",
    nameHe: "מזרן שינה מתנפח אולטרה-קליל לקמפינג",
    nameEn: "Ultralight Inflatable Camping Sleeping Pad",
    descriptionHe:
      "מזרון שינה מתנפח ונוח, מבודד קור, קליל במיוחד ומתקפל לגודל בקבוק שתייה. מושלם לקמפינג וטרקים ארוכים.",
    category: "sleep-comfort",
    cjPid: "1376507432263618560",
    cjVid: "1376507433647738880",
    costUsd: 11.49,
    shippingUsd: 12.72,
    etaDays: [9, 23],
    priceSource: "cj-live",
    icon: "sleeping-pad",
    imageUrl: "https://cf.cjdropshipping.com/aec9f308-80aa-4caf-ae51-4a818f86c7ee.jpg",
    specsHe: ["בידוד תרמי", "מתנפח ידנית תוך דקות", "מתקפל לגודל קומפקטי"],
    packageContentsHe: ["מזרן שינה מתנפח עם משאבה מובנית - יחידה אחת"],
  },
  {
    slug: "led-mosquito-camping-lantern",
    nameHe: "פנס קמפינג עם קוטל יתושים LED",
    nameEn: "LED Camping Lantern with Mosquito Killer",
    descriptionHe:
      "פנס קמפינג נטען המשלב תאורת LED וקוטל יתושים אלקטרוני - שומר על האוהל מואר ונקי מחרקים לאורך כל הלילה.",
    category: "lighting",
    cjPid: "2406210707081605000",
    cjVid: "2406210707081605300",
    costUsd: 5.47,
    shippingUsd: 6.69,
    etaDays: [22, 27],
    priceSource: "cj-live",
    icon: "bug-lantern",
    imageUrl: "https://oss-cf.cjdropshipping.com/product/2024/06/21/07/27f70915-b386-4699-bd18-6d7f7ca814bf.jpg",
    specsHe: ["קוטל יתושים אלקטרוני מובנה", "נטען USB", "וו תלייה לאוהל"],
    packageContentsHe: ["פנס קמפינג עם קוטל יתושים - יחידה אחת"],
  },
  {
    slug: "folding-portable-bbq-grill",
    nameHe: "מנגל פחמים מתקפל וניידת לקמפינג",
    nameEn: "Folding Portable Charcoal BBQ Grill",
    descriptionHe:
      "מנגל פחמים קומפקטי ומתקפל מנירוסטה, קל להרכבה ולפירוק - אידיאלי לטיולי שטח, חופים וקמפינג משפחתי.",
    category: "cooking",
    cjPid: "1382251561337622528",
    cjVid: "1382251562839183360",
    costUsd: 1.21,
    shippingUsd: 8.68,
    etaDays: [9, 23],
    priceSource: "cj-live",
    icon: "grill",
    imageUrl: "https://cf.cjdropshipping.com/1618389070445.jpg",
    specsHe: ["גוף נירוסטה עמיד", "מתקפל תוך שניות", "כולל תיק נשיאה"],
    packageContentsHe: ["מנגל מתקפל - יחידה אחת", "תיק בד לנשיאה"],
  },
  {
    slug: "portable-cookware-mess-kit",
    nameHe: "סט כלי בישול ניידים לקמפינג",
    nameEn: "Portable Camping Cookware Mess Kit",
    descriptionHe:
      "סט סירים וכלי אכילה קומפקטי מאלומיניום קל משקל, כולל תיק נשיאה - כל מה שצריך לבישול בשטח.",
    category: "cooking",
    cjPid: "0353779C-FBD2-4EFF-9097-85C346DE1E61",
    cjVid: "1459808907370303489",
    costUsd: 3.97,
    shippingUsd: 7.33,
    etaDays: [9, 23],
    priceSource: "cj-live",
    icon: "cookware",
    imageUrl: "https://cf.cjdropshipping.com/20200904/623002509239.jpg",
    specsHe: ["אלומיניום אנודייז קל משקל", "כולל סיר, מחבת וכלי אכילה", "מתקפל לגודל קומפקטי"],
    packageContentsHe: ["סיר עם מכסה", "מחבת", "כפית, סכין ומזלג מתקפלים", "תיק נשיאה"],
  },
  {
    slug: "multi-tool-survival-knife",
    nameHe: "כלי רב-תכליתי להישרדות וקמפינג",
    nameEn: "Multi-Tool Survival Camping Knife",
    descriptionHe:
      "כלי רב-תכליתי קומפקטי הכולל סכין, פותחן, מברג ועוד - ציוד בסיס לכל תיק קמפינג או תיק חירום.",
    category: "tools-safety",
    cjPid: "1408262032565866496",
    cjVid: "1408262033991929856",
    costUsd: 6.64,
    shippingUsd: 0,
    etaDays: [0, 0],
    priceSource: "cj-live",
    shipsToIsrael: false,
    icon: "multi-tool",
    imageUrl: "https://cf.cjdropshipping.com/585655aa-f898-40b1-ab8a-297718c31f59.jpg",
    specsHe: ["פלדת נירוסטה", "מספר כלים במכשיר אחד", "כולל נרתיק נשיאה"],
    packageContentsHe: ["כלי רב-תכליתי - יחידה אחת", "נרתיק נשיאה"],
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.featured);
}
